unifi:
  endpoint: https://192.168.0.1
  username: username
  password: password

dns:
  resolver:
    network: udp
    address: 1.1.1.1:53
    timeout: 10
  groups:
    - site: default
      id: 123456789abcdef987654321
      hosts:
        - www.example.org

webhook:
  enabled: true