name: Docker Image CI

on:
  workflow_dispatch:

env:
  VERSION: 2.0.2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm,linux/arm64
          tags: suncj98/unifi-ipv6-firewall-updater:latest,suncj98/unifi-ipv6-firewall-updater:${{ env.VERSION }}
